#!/usr/bin/python3

import os
import librungame.util
import librungame.game
import librungame.runner

if __name__ == "__main__":
    selfDir = os.path.dirname(os.path.realpath(__file__))
    sysInfo = librungame.util.SysInfo()
    game = librungame.game.Factorio("/opt/factorio")
    runner = librungame.runner.DirectNonStandard("factorio", game, sysInfo)
    runner.run()
