#!/usr/bin/python3

import os
import librungame.util
import librungame.runner
import librungame.game.linux

if __name__ == "__main__":
    selfDir = os.path.dirname(os.path.realpath(__file__))
    sysInfo = librungame.util.SysInfo()
    game = librungame.game.linux.Factorio("/opt/factorio")
    runner = librungame.runner.Direct("factorio", game, sysInfo)
    runner.run()
