# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

PYTHON_COMPAT=( python3_{11..14} )
DISTUTILS_USE_PEP517=setuptools
inherit distutils-r1 git-r3

DESCRIPTION="Download market data from Yahoo! Finance's API"
HOMEPAGE="https://ranaroussi.github.io/yfinance"
EGIT_REPO_URI="mirror://github/ranaroussi/yfinance.git"

LICENSE="GPL-3+"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

DEPEND="dev-python/setuptools[${PYTHON_USEDEP}]"
RDEPEND=""
