# automatically generated by g-sorcery
# please do not edit this file

EAPI=8
PYTHON_COMPAT=( python{2_7,3_6,3_7,3_8,3_9,3_10,3_11,3_12,3_13} )
DISTUTILS_USE_PEP517=setuptools

inherit distutils-r1

DESCRIPTION="Implements some tools for JSON"
SRC_URI="https://files.pythonhosted.org/packages/4d/47/84e030fb7764bd716d2fb58d4bd45c006b407cd413f472a60f1e09265ceb/json_spec-0.12.0.tar.gz"

HOMEPAGE="http://py.errorist.io/json-spec"
LICENSE="Apache-2.0"

SLOT="0"
KEYWORDS="~amd64 ~x86"

