# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

PYTHON_COMPAT=( python3_{11,14} )
DISTUTILS_USE_PEP517=setuptools
inherit distutils-r1 git-r3

DESCRIPTION="Python Backtesting library for trading strategies"
HOMEPAGE="https://www.backtrader.com"
EGIT_REPO_URI="mirror://github/mementum/backtrader.git"

LICENSE="GPL-3+"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="plotting"

DEPEND="dev-python/setuptools[${PYTHON_USEDEP}]"
RDEPEND="plotting? ( dev-python/matplotlib[${PYTHON_USEDEP}] )"
